# Generated by Django 3.0.3 on 2020-02-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20200225_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
