# Generated by Django 3.0.3 on 2020-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200226_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='nmb',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='uptated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
